name: Build and Deploy
on: 
push: 
  branches:
    -main

jobs: 
  build-and-deploy:
  runs-on: ubuntu-latest
  concurrency: ci:${{github.ref}}
  steps:
    - name: Checkout
      uses: actions/setup-node@v1
      with:
        node-version: '22.16.0'
    
    - name: Install
      run: |
        npm ci
        npm run build

    - name: Deploy
      uses: tsg_collapp-web/githu-pages-deploy-action@v4
      with: 
        folder: build
        branch: gh-pages
    